import streamlit as st

def Porti():
    st.write('Olá! Muito Prazer me chamo Luciano de Andrade Borba, sou casado, tenho 3 filhos, sou uma pessoa apaixonada pela área de Tecnologia, em especial área de Dados, amo agregar valor através das minhas análises, assim impactando no dia a dia das pessoas!')
    st.write('')
    st.write('Trabalho na **Secretaria Municipal de Saúde de João Pessoa**, sou _Data Analytics_, atuo analisando dados organizacionais para auxiliar no planejamento financeiro da Secretaria.')
    st.write('')
    st.write('**-Tecnologia Utilizada: (Lista em Ordem de Experiência, Utilização e Habilidade)**')
    st.write('-Linguagem Python')
    st.write('-PowerBI')
    st.write('-Excel/Google Sheets')
    st.write('-SQL Server')
    st.write('-MySQL')
    st.write('-Oracle Database')
    st.write('-Oracle Apex (Low Code)')
    st.write('-Tableau Public')
    st.write('-Linguagem R')
    st.subheader('**Formação Acadêmica**')
    st.write('**-Formado em Gestão da Tecnologia da Informação - Nível Tecnologo - FPB - 2012.1 a 2014.1**')
    st.write('**-Em Andamento - Pós-Graduação em Analise de Dados - Descomplica - 03/2022**')
    st.write('**-Em Andamento - MBA em Business Intelligence - Descomplica - 04/2022**')
    st.subheader('**Experiência**')
    st.write('**-Analista de Dados - Secretaria Municipal de Saúde de João Pessoa - 01/04/2022 [Emprego Atual]*')
    st.write('Atuando com Dados em grande volume, com foco para planejamento organizacional para planejamentos, mas mediante ao projeto analisando dados dos cidadões para melhor planejamento de ações de Saúde na cidade')
    st.write('**-Técnico de Suporte a Sistemas - Secretaria Municipal de Saúde de João Pessoa - 01/01/2021 a 31/03/2022** ')
    st.write('Atuando com Treinamento, Suporte HelpDesk, Suporte Remoto, geração de relatório e dashboards')
    st.write('**-Técnico de Informática - Secretaria Municipal de Saúde de João Pessoa - 04/04/2018 a 31/12/2020**')
    st.write('Atuando com HelpDesk, Suporte de Software, Elaboração de Material para Suporte, Elaboração Termos para Contratação/Aquisição de Equipamentos e Suprimento de informática ')
    st.subheader('**-Cursos Complementares**')
    st.write('-Introdução ao Tableau - 5 Horas - EIA[04/2022]')
    st.write('-Machine Learning com Python - 3 Horas - Regressão Linear - DataViking[04/2022]')
    st.write('-SQL com Python - 3 Horas - DataViking[04/2022]')
    st.write('-Microsoft PowerBI para DataScience - 72 Horas - DataScience Academy[04/2022]')
    st.write('-Visualização de Dados(DataViz) - 10Horas - Estidados[04/2022]')
    st.title('Página de Portifolio de Tarefas de Análise de Dados Usando o Python')
    st.subheader('Me siga no Linkedin: www.linkedin.com/in/luhborba')
    st.subheader('Entra lá no meu Canal do Youtube: https://www.youtube.com/channel/UCN16u-GFjdNmVWlxBZvRqsQ')
    