import streamlit as st

def Porti():
    st.write('Olá! Muito Prazer me chamo Luciano de Andrade Borba, sou casado, tenho 3 filhos, sou uma pessoa apaixonada pela área de Tecnologia, em especial área de Dados, amo agregar valor através das minhas análises, assim impactando no dia a dia das pessoas!')
    st.write('')
    st.write('Trabalho na **Secretaria Municipal de Saúde de João Pessoa**, sou _Data Analytics_ atuo analisando dados organizacionais para auxiliar no planejamento financeiro da Secretaria.')
    st.write('')
    st.write('**-Tecnologia Utilizada: (Lista em Ordem de Experiência, Utilização e Habilidade)**')
    st.write('-Linguagem Python')
    st.write('-PowerBI')
    st.write('-Excel/Google Sheets')
    st.write('-SQL Server')
    st.write('-MySQL')
    st.write('-Oracle Database')
    st.write('-Oracle Apex (Low Code)')
    st.write('-Tableau Public')
    st.write('-Linguagem R')
    st.subheader('**Formação Acadêmica**')
    st.write('**-Formado em Gestão da Tecnologia da Informação - Nível Tecnologo - FPB - 2012.1 a 2014.1**')
    st.write('**-Em Andamento - Pós-Graduação em Analise de Dados - Descomplica - 03/2022**')
    st.write('**-Em Andamento - MBA em Business Intelligence - Descomplica - 04/2022**')
    st.title('Página de Portifolio de Tarefas de Análise de Dados Usando o Python')
    st.subheader('Me siga no Linkedin: www.linkedin.com/in/luhborba')
    st.subheader('Entra lá no meu Canal do Youtube: https://www.youtube.com/channel/UCN16u-GFjdNmVWlxBZvRqsQ')